### ISSUE TITLE
Setup plausible account for GHE and integrate JS script into openwashdata website and packages

### ISSUE THREAD

**Issue by larnsce** [openwashdata/book#28]
Example for `pkgdown` package template

**https://github.com/tidyverse/tidytemplate/blob/main/_pkgdown.yml**

Example for quarto html files:

```
format:
  html:
    include-in-header:
      - text: |
          <script src="https://examples.org/demo.js"></script>
```

Source: https://quarto.org/docs/output-formats/html-basics.html#includes
